#!/bin/bash

pdftk tafsir.pdf cat 35-1009 output temporaer.pdf &&
pdftk temporaer.pdf burst &&
for f in pg_*.pdf; do 
  pdftotext -layout "$f" - | sed "s/Tafsīr Al-Qur’ān Al-Karīm//g" > "${f%.pdf}.txt";
done &&
rm pg_*.pdf doc_data.txt temporaer.pdf
