#!/bin/bash
#
# ...existing code...
pdftk tafsir.pdf cat 35-1009 output temporaer.pdf &&
pdftk temporaer.pdf burst &&
for f in pg_*.pdf; do 
  # Entferne Titel und (ÜB) beim Export; akzeptiert Groß-/Kleinschreibung und U/Ü
  pdftotext -layout "$f" - | \
    sed "s/Tafsīr Al-Qur’ān Al-Karīm//g" | \
    sed -E 's/\(\s*[ÜüUu]\s*[Bb]\s*\)//g' > "${f%.pdf}.txt";
done &&
rm pg_*.pdf doc_data.txt temporaer.pdf
# ...existing code...